markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: DevAI

# MCP Integration Configuration
mcp:
  enabled: true
  port: 3000
  resources:
    - policy
    - knowledge-base
    - templates
    - workflows
    - agents
    - tasks
    - checklists
    - technical-preferences
    - manifest
  tools:
    - policy-validator
    - agent-switch
    - agent-list
    - shard-doc
    - story-manager
    - workflow-executor
    - git-workflow
    - test-runner
